### ISSUE TITLE
airfoils path issues

### ISSUE THREAD

**Issue by neosoyo** [pedrosecchi67/LovelacePM#4]
lovelace can't find airfoils .dat files:
FileNotFoundError: [Errno 2] No such file or directory: 'onerad.dat'

**Comment by neosoyo** [comment]
only runs if i copy the .dat files from lovelacepm installation dir to my local dir. Ubuntu 19.10

**Comment by neosoyo** [comment]
there is no .dat files from pip3 installation

**Comment by pedrosecchi67** [comment]
Hi!

The package fetches airfoil files from your current directory by default: in the README onera M6 example there's an explanaition about that, but I forgot to add them to the tutorials too. I'll add more detail to them.
What the example and test case scripts (`testcase_oneram6`, `testcase_n0012_rotating` and a couple of others) do in order to use files in the source folder is to use `os.chdir(os.path.abspath(__file__))` to move to that folder and roll back that action after the example is ran.
It wouldn't be hard to reprogram the package to search in its source folder if the airfoils are not found in your current folder, would that be good?
The airfoil files are included in the MANIFEST.in file, so they should be included in the PyPi package. I've checked the .tar file that I uploaded as a source distribution and they're there. Yet I've just downloaded the package to test it and they indeed don't seem to be in the package's folder, as you said, though... I'll try to find out what's happening and why they're not being unpacked from the tar along with the source files and I'll tell you as soon as I can fix it

**Comment by pedrosecchi67** [comment]
I've just corrected the .dat files not included on source distribution error, there was a missing argument in `setup.py` to include those files to the source distribution. Should be corrected on PyPi as version v0.1.9 is uploaded tonight (:

**Comment by pedrosecchi67** [comment]
Solved! Version v0.1.9 now searches the package folder for airfoils if they aren't found in your current directory. I've also made the tutorial clearer in specifying the files should be there. They're also now correctly included in the source distribution on PyPi, as I've said above.
Enjoy :)
